# Generated by Django 5.0.7 on 2024-07-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bread',
            name='image_url',
        ),
        migrations.AddField(
            model_name='bread',
            name='img_src',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='bread',
            name='tags',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='bread',
            name='category',
            field=models.CharField(choices=[('bread', '식빵'), ('baguette', '바게트'), ('bagel', '베이글'), ('cake', '케이크'), ('donut', '도넛'), ('cream', '크림빵'), ('root_vegetable', '구황작물빵'), ('special', '기획전')], max_length=20),
        ),
    ]
