# Generated by Django 5.0.6 on 2024-07-31 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0002_remove_bread_image_url_bread_img_src_bread_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bread',
            name='description',
        ),
        migrations.AddField(
            model_name='bread',
            name='description1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bread',
            name='description2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bread',
            name='description3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
