# Generated by Django 5.0.6 on 2024-08-01 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0003_remove_bread_description_bread_description1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bread',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
