# Generated by Django 5.0.7 on 2024-07-29 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0002_remove_bread_image_url_bread_img_src_bread_tags_and_more'),
        ('breadtypefinder', '0003_resulttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreadRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakery.bread')),
                ('result_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bread_recommendations', to='breadtypefinder.resulttype')),
            ],
        ),
    ]
