# Generated by Django 5.0.6 on 2024-07-31 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='breaddiary',
            name='img_src',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=''),
        ),
    ]
