# Generated by Django 5.0.7 on 2024-07-24 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('quantity', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('image', models.URLField()),
                ('title', models.CharField(max_length=255)),
                ('tags', models.CharField(max_length=255)),
                ('cooking_time', models.CharField(max_length=50)),
                ('equipment', models.CharField(max_length=255)),
                ('ingredients', models.ManyToManyField(to='recipes.ingredient')),
                ('steps', models.ManyToManyField(to='recipes.step')),
            ],
        ),
    ]
