# Generated by Django 5.0.7 on 2024-07-23 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='name',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='cook_time',
            new_name='cookingTime',
        ),
        migrations.RenameField(
            model_name='step',
            old_name='instruction',
            new_name='description',
        ),
    ]
