# Generated by Django 5.0.7 on 2024-07-26 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_bookmark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='cooking_time',
            new_name='cookingTime',
        ),
    ]
